@startuml

class ユーザー
class 記事
class コメント
class マガジン
class タグ
class ジャンル

class 支払先 {
 - 銀行コード
 - 支店コード
 - 口座番号
}
note left of 支払先 : サービス上で得た報酬を振り込む先の情報

class 個人支払先 {
 - 姓
 - 名
}
class 法人支払先 {
 - 法人名
}

note top of カード情報 : サービス上で支払を行うための情報
class カード情報 {
 - カード番号
 - カード名義
}
ユーザー "1" -up- "0..1" カード情報

ユーザー "1" -up- "0..1" "支払先"
"個人支払先" --|> "支払先"
"法人支払先" --|> "支払先"

ユーザー "1" -- "*" 記事
記事 "1" -- "*" コメント
ユーザー "1" -- "*" コメント

ジャンル "1..*" -- "*" 記事

タグ "*" -- "*" 記事

マガジン "0..1" -- "*" 記事

package リアクション {
   class サポート {
       - サポートするユーザー
       - サポートされるユーザー
       - 金額
   }
   ユーザー "1" --> "*" サポート
   サポート "*" --> "1" ユーザー

   class フォロー {
       - フォローするユーザー
       - フォローされるユーザー
   }

   (ユーザー, ユーザー).. フォロー

   class スキ
   ユーザー "1" -- "*" スキ
   スキ "*" -- "1" 記事
}


class SNSアカウント
ユーザー "1"-up-"*" SNSアカウント
class Twitterアカウント
class Facebookアカウント
Twitterアカウント --|> SNSアカウント
Facebookアカウント --|> SNSアカウント

@enduml